In [2]:
#from google.colab import drive
#drive.mount("/content/drive")
%cd "drive/MyDrive/COMP2211"
%ls
import numpy as np
# delimiter: The string used to separate values. As ',' is used as delimiter in csv, we specify delimiter as ','
# skiprows: Skip the first skiprows lines; default: 0. As we want to skip the header row, we specify skiprows as 1 
train = np.loadtxt("heart2_train.csv", delimiter=',', skiprows=1)
test = np.loadtxt("heart2_test.csv", delimiter=',', skiprows=1)


In [3]:
# The given code below calculates the Prior Probabilities of Heart Disease.
# Modify the code to also calculate the Likelihoods for all the remaining features.
train_labels = train[:, -1]                # Only the last column
num_heart_disease_yes=sum(train_labels==1) # Use elementwise checking and sum to find number of matching elements
num_heart_disease_no=sum(train_labels==0)  # Use elementwise checking and sum to find number of matching elements

# Get the Prior Probability P(label)
heart_disease_yes = num_heart_disease_yes/train.shape[0] # P(heart_disease = yes)
heart_disease_no = num_heart_disease_no/train.shape[0]   # P(heart_disease = no)

In [4]:
train.shape

(925, 8)

In [5]:
feature_labels_yes = train[:,:-1][train[:,-1] ==1].transpose((1,0))
feature_labels_no = train[:,:-1][train[:,-1] ==0].transpose((1,0))

In [11]:
feature_labels_yes.shape

(7, 472)

In [30]:
k = int(np.max(feature_labels_yes))
num_feature_labels_yes = np.zeros((feature_labels_yes.shape[0],k+1))
num_feature_labels_no = np.zeros((feature_labels_yes.shape[0],k+1))

In [31]:
k

3

In [32]:
num_feature_labels_yes

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [47]:
feature_labels_yes

array([[0., 0., 0., ..., 1., 1., 1.],
       [0., 0., 1., ..., 2., 1., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 1., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 3., 2.]])

In [44]:
num_feature_labels_yes = [[(row == i).sum() for i in range(k + 1)] for row in feature_labels_yes]
num_feature_labels_no = [[(row == i).sum() for i in range(k + 1)] for row in feature_labels_no]

In [45]:
num_feature_labels_yes

[[203, 269, 0, 0],
 [104, 124, 198, 46],
 [411, 61, 0, 0],
 [197, 273, 2, 0],
 [406, 66, 0, 0],
 [26, 140, 306, 0],
 [3, 19, 375, 75]]

In [61]:
num_feature_labels_no

[[78, 375, 0, 0],
 [336, 31, 62, 24],
 [377, 76, 0, 0],
 [262, 182, 9, 0],
 [206, 247, 0, 0],
 [42, 291, 120, 0],
 [4, 40, 122, 287]]

In [62]:
total = np.sum(num_feature_labels_yes,axis = 1)[0]
total_2 = np.sum(num_feature_labels_no,axis = 1)[0]
print(total)
print(total_2)

472
453


In [88]:
prob = [[(1) if i == 0 else (i) for i in row ] for row in num_feature_labels_yes/total]
prob_2 = [[(1) if i == 0 else (i) for i in row ] for row in num_feature_labels_no/total_2]
print(prob)
print(prob_2)

[[0.4300847457627119, 0.5699152542372882, 1, 1], [0.22033898305084745, 0.2627118644067797, 0.4194915254237288, 0.09745762711864407], [0.8707627118644068, 0.1292372881355932, 1, 1], [0.4173728813559322, 0.5783898305084746, 0.00423728813559322, 1], [0.8601694915254238, 0.13983050847457626, 1, 1], [0.05508474576271186, 0.2966101694915254, 0.6483050847457628, 1], [0.006355932203389831, 0.04025423728813559, 0.7944915254237288, 0.15889830508474576]]
[[0.17218543046357615, 0.8278145695364238, 1, 1], [0.7417218543046358, 0.0684326710816777, 0.1368653421633554, 0.052980132450331126], [0.8322295805739515, 0.16777041942604856, 1, 1], [0.5783664459161147, 0.40176600441501104, 0.019867549668874173, 1], [0.45474613686534215, 0.5452538631346578, 1, 1], [0.09271523178807947, 0.6423841059602649, 0.26490066225165565, 1], [0.008830022075055188, 0.08830022075055188, 0.2693156732891832, 0.6335540838852097]]


In [90]:
log_prob = np.log(prob)
log_prob_2 = np.log(prob_2)

In [91]:
def predict(row):
    count_yes = log_heart_disease_yes
    count_no = log_heart_disease_no
    i = 0
    for j in row:
        j = int(j)
        count_yes = count_yes + log_prob[i][j]
        count_no = count_no + log_prob_2[i][j]
        i = i + 1
#TODO:
    
    prediction = (count_yes > count_no)
    # Return the prediction value
    return [prediction, count_yes]

In [92]:
# The given code below sums the log-prior-probability of Heart Disease.
# Finish the above function to also sum the log-likelihoods for all the remaining features, 
# according to the specific test case. 
test_features = test[:, :-1]  # All except the last column.
test_labels = test[:, -1]     # Only the last column.

predict_labels = np.zeros_like(test_labels)       # Create a numpy array of zeros with the same shape as test_labels. 

log_heart_disease_yes = np.log(heart_disease_yes) # log_e of P(heart_disease = yes)
log_heart_disease_no = np.log(heart_disease_no)   # log_e of P(heart_disease = no)

In [97]:
test_features

array([[1., 0., 0., 1., 1., 1., 3.],
       [1., 0., 0., 0., 1., 1., 2.],
       [1., 2., 1., 1., 0., 0., 3.],
       [1., 0., 0., 0., 1., 1., 3.],
       [1., 0., 0., 0., 1., 1., 3.],
       [1., 0., 0., 0., 0., 1., 3.],
       [1., 0., 0., 1., 0., 2., 3.],
       [0., 2., 0., 0., 0., 2., 2.],
       [1., 3., 0., 1., 1., 1., 3.],
       [1., 2., 0., 1., 0., 2., 2.],
       [1., 1., 0., 1., 0., 0., 2.],
       [1., 2., 0., 1., 0., 2., 2.],
       [1., 2., 0., 1., 0., 2., 2.],
       [1., 0., 0., 0., 1., 2., 3.],
       [0., 1., 0., 1., 0., 1., 2.],
       [0., 0., 0., 1., 1., 1., 3.],
       [0., 2., 0., 0., 0., 1., 2.],
       [0., 3., 0., 1., 0., 2., 2.],
       [1., 0., 0., 1., 0., 2., 3.],
       [0., 0., 1., 1., 1., 1., 3.],
       [1., 3., 0., 0., 0., 1., 3.],
       [0., 2., 0., 1., 0., 2., 2.],
       [0., 2., 0., 1., 0., 2., 2.],
       [1., 0., 0., 1., 1., 0., 3.],
       [1., 0., 0., 1., 1., 2., 3.],
       [1., 0., 0., 0., 1., 1., 2.],
       [0., 2., 0., 1., 0., 1., 3.],
 

In [96]:
test_features.shape

(100, 7)

In [93]:
for row in range(test_features.shape[0]):
    prediction=predict(test_features[row])
    predict_labels[row] = prediction[0]

In [94]:
num_match = 0
for i in range(predict_labels.shape[0]):
    if predict_labels[i] == test_labels[i]:
       num_match += 1

accuracy_score = num_match/predict_labels.shape[0]

print(accuracy_score)


0.78


In [16]:
drive.flush_and_unmount()

NameError: name 'drive' is not defined